### PR TITLE
 #1 removed facebook url

### PR DESCRIPTION
**Pull request by andreicristianpetcu**

### CODE REVIEW

**Comment by andreicristianpetcu** [comment]
@idlewan do I need to do anything extra for this pull request to be accepted?
Thank you!

**Comment by idlewan** [comment]
Nope, LGTM!

**Comment by andreicristianpetcu** [comment]
Great then! How about getting rid of the Reddit redirects now? :D

https://out.reddit.com/t3_5pq7qd?url=https%3A%2F%2Finternethealthreport.org%2Fv01%2F&token=AQAAZV6JWHBBnIcVjV1wvxVg5gKyCQQSdUhGIvuEUmdPZhxhm8kH&app_name=reddit.com

If I make another pull request and it gets accepted then I can get rid of a addon I use to get rid of these redirects :D

**Comment by idlewan** [comment]
Go for it!

It didn't even occur to me before that it could be useful for that. Getting rid of those pesky "oh so you want to go to another website?" pages is a great idea (steam, reddit, youtube, I'm looking at you).

**Pull request merged**
